### ISSUE TITLE
Build institutional user lists (when pressbooks network analytics is active)

### ISSUE THREAD

**Issue by SteelWagstaff** [pressbooks/pressbooks-multi-institution#41]
As an institutional manager, I should see a user list with information specific to my institution after logging into to Pressbooks. See https://www.figma.com/file/hAvkPJpDgJDDyh8g358AqR/PB-Site-Adjustments?type=design&node-id=15-2447&mode=design&t=z2fac24aKvMfKhze-0

![Screenshot from 2024-02-14 07-11-53](https://github.com/pressbooks/pressbooks-multi-institution/assets/13485451/a60cb097-46d1-4e8c-9f55-90f8d7a66e20)

The text at the top of the user list should be specific to the particular institution. Only users which are assigned to the institution should be displayed in the list and available to the search/filter tools provided by this page. 

DoD: 
1. The default user list should have a new 'institution' column that displays when this plugin is active for all users
2. We need to add institution filters for super admins/network managers
3. When an institutional manager loads the user list, they should see the custom version of the list with relevant information only for their institution
4. Institutional managers should be able to the search, filter, and download CSV features of the existing user list without special restrictions. These actions should only affect users in their user list.
5. Institutional managers should not be able to see the network user list or the user list for other institutions that they don't have access to.

Do we need a data collector to store the institution ID in a centralized data table?

## Notes
My idea was that every institution would have their own user list page (each one would have an institution ID parameter in the URL). Institutional managers would get routed to the relevant institutional user list when clicking the link from their dashboard or nav menu. Super admins and network managers could view these pages by entering the URL directly and would see the same thing that the institutional managers sees.

**Comment by richard015ar** [comment]
I created a video to avoid a meeting, so you can watch (optional) the implementation I did for users list. Background info:
- Draft PR based on bro's branch: https://github.com/pressbooks/pressbooks-multi-institution/pull/56
- Analytics PR (I just added on top of bro's branch): https://github.com/pressbooks/pressbooks-network-analytics/pull/331
- Video: 
[Users list in PB analytics with Instituion field and filter.webm](https://github.com/pressbooks/pressbooks-multi-institution/assets/13248424/3ee92e5d-9d08-4b21-905b-d49524f6a7c0)

### Testing case for this WIP in ricardodev
**Note: The search is in progress, I'm on it. It does not work at the moment.**
- Log in as an Institutional Manager
- Go to Users > Network Users
- Make sure you can only see users from the institutions you belong to
- You should be able to see a new column `Institution` after `Email` column in the users table.
- Log in as a super admin or network manager and go to Users > Network Users
- You should be able to see the Institution column, and you should be able to order by this column
- A new filter should appear `Institutions:`, it's a selector with all the institutions available.
- Filter and make sure the filter works as expected.

**Comment by tw77** [comment]
Early testing on ricardodev blocker described at https://pressbooks.slack.com/archives/CCWPHQY83/p1708545587482889?thread_ts=1708541683.619089&cid=CCWPHQY83

**Comment by tw77** [comment]
Unblocked, following steps: as institutional manager **ricardo015ar** everything works as expected.

As institutional manager **thomasnew2**, there seems to be a glitch because this user belongs to a different institution than the one they're an institutional manager for. **thomasnew2** sees users from both institutions in the user list. I'm not sure how that happened.

The super admin testing steps work as expected. I see there isn't an option to filter by unassigned, but I don't know if that's planned or not. I can't download a CSV of users from my institution (tried this as **ricardo015ar** ) but I assume this isn't implemented yet.

**Comment by richard015ar** [comment]
The tests for the changes were added. In addition, I also added the `Unassigned` filter for super admin in the Users list (network analytics).

Everything ready to test at ricardodev network.

Pending:
- CSV export.
- Add CSV related tests.
- Fix for users count displayed at the top of the users list page, it does not display the number of users correctly now. (Legend: `There are X users in this network.`).

**Comment by tw77** [comment]
Unassigned filter in the Users list is working on ricardodev.

**Comment by richard015ar** [comment]
CSV, pending tests and a fix for the users' count are ready for testing at ricardodev.

All the changes in: https://github.com/pressbooks/pressbooks-multi-institution/pull/56, waiting for a meeting with devs to decide on how to proceed with merging this and other pending changes.

**Comment by tw77** [comment]
Clicking the Download CSV button in https://ricardodev.pressbooks.network/wp/wp-admin/admin.php?page=pb_network_analytics_userlist as an institutional manager user isn't prompting a download of a file for me

**Comment by richard015ar** [comment]
Thank you Thomas, I just fixed that.
I also this morning improved some performance issue, and now I adjusted the permissions to allow users to edit and delete other users form the list and implement the necessary restrictions.
I also fixed the search action.

**Comment by tw77** [comment]
@richard015ar This may be already known but as an institutional manager user (thomasnew1), I'm still seeing a user from a different institution (ricardostudent2) in https://ricardodev.pressbooks.network/wp/wp-admin/admin.php?page=pb_network_analytics_userlist . This unexpected user appears in the CSV download too, which is otherwise working.

**Comment by tw77** [comment]
Works as expected testing on dev.
